---
title: "Uganda historical mean t and precip graphs"
output: html_notebook
---


```{r}
library(ggplot2) 
library(tidyr)
library(dplyr)
library(scales)  #for sec axis
library(berryFunctions) # for the last two maps
```

# Read data

The file below contains monthly data for Uganda between 1979-2014. 

```{r}
data <- read.csv("1979-2019_monthly_Uganda.csv", header = TRUE)
# head(data)
# data format:
# lon | lat | year | month | pr | tasmin | tasmax
```

# Prepare data

Get monthly mean t and rainfall across all years. 

```{r}
# Precipitation
monthly_pr<-aggregate(pr ~ month, data=data, mean, na.rm=TRUE)
# data format:
# month | pr

# for checking pr.where(month == 1) = 43.67578
# pr_1 <- filter(data, month==1)
# pr_1 <- select(pr_1, month, pr)
# pr_1_mean <- aggregate(pr~month, data=pr_1, mean, na.rm=TRUE) 

# Temperature
monthly_tas<-aggregate(cbind(tasmax,tasmin) ~ month, data=data, mean, na.rm=TRUE)
monthly_tas$tas<-rowMeans(monthly_tas[,c('tasmin','tasmax')], na.rm=TRUE)               # mean t for given month
# data format:
# month | tas | tasmin | tasmax

# for checking tas.where(month == 1): tasmax=31.1976 and tasmin=16.87967, tas = 24.03864
#tas_1 <- filter(data, month==1)
#tas_1 <- select(tas_1, month, tasmin, tasmax)
#tas_1_mean <- aggregate(cbind(tasmax,tasmin)~month, data=tas_1, mean, na.rm=TRUE)

# Combine
monthly_hist_means<-monthly_pr
monthly_hist_means$tas<-monthly_tas$tas
# data format:
# month | pr | tas
```


# Derive graph 

## For entire Uganda:
```{r}
map_hist_mean <- 
  ggplot(data=monthly_hist_means, aes(x=month)) +
  geom_bar(stat="identity", aes(y=pr))+ 
  geom_point(aes(y = tas* 6), color="#008080", size=2) + 
  geom_smooth(aes(y = tas * 6), color="#008080", size=1) +
  scale_x_continuous(breaks = pretty_breaks()) + # to get rid of doubles on the x axis
  scale_y_continuous(name="Precipitation", sec.axis = sec_axis(~ . / 6, name="Temperature"))+
  theme_bw()+
  theme(strip.text.x = element_text(size = 12, face = 'bold', family="DejaVu Sans")) +
  theme(strip.text.y = element_text(size = 12, face = 'bold', family="DejaVu Sans"))
plot(map_hist_mean)
```

## For selected points

Point in the northern part: lat=3.25, lon=33.25
Point for the southern part: lat=-0.25, lon=31.25

### Prepare data
```{r}
# Since previous aggregations didn't take lon+lat into consideration, re-do some steps here
north_monthly<-filter(data, lat==3.25, lon==33.25)
# data format:
# lon | lat | year | month | pr | tasmin | tasmax
north_monthly_pr<-aggregate(pr ~ month, north_monthly, mean, na.rm=TRUE)
# data format:
# month | pr 
north_monthly_tas<-aggregate(cbind(tasmax,tasmin) ~ month, north_monthly, mean, na.rm=TRUE)
north_monthly_tas$tas<-rowMeans(north_monthly_tas[,c('tasmin','tasmax')], na.rm=TRUE)
# data format:
# month | tas | tasmin | tasmax


south_monthly<-filter(data, lat== -0.25, lon==31.25)
south_monthly_pr<-aggregate(pr ~ month, south_monthly, mean, na.rm=TRUE)
south_monthly_tas<-aggregate(cbind(tasmax,tasmin) ~ month, south_monthly, mean, na.rm=TRUE)
south_monthly_tas$tas<-rowMeans(south_monthly_tas[,c('tasmin','tasmax')], na.rm=TRUE)
```

### Derive graphs for specific points
```{r}
# change the mtext to m of Uganda
climateGraph(north_monthly_tas$tas,north_monthly_pr$pr,main = "      ",coltemp = "red3",colrain = "blue", argtext=list(cex=0.7), ylim=c(1,80), lwd=3, compress=FALSE, textprop=0.4)
mtext("1029 m", col=1, at=6.5, line=1, cex=1, font=1)

climateGraph(south_monthly_tas$tas,south_monthly_pr$pr,main = "      ",coltemp = "red3",colrain = "blue", argtext=list(cex=0.7), ylim=c(1,80), lwd=3, compress=FALSE, textprop=0.4)
mtext("1318 m", col=1, at=6.5, line=1, cex=1, font=1)

```

