---
title: "Uganda hist data t and precip maps"
author: "Albina Muzafarova"
output: html_notebook
---

```{r}
library(ggplot2) #for mapping with ggplot
library(scales)  #for colour scales
library(RColorBrewer) #for colour scales
library(rgdal) #reading shape files
library(tidyr)
library(dplyr)
```

# Import data

The file below contains monthly data for Uganda between 1979-2014. 

```{r}
data <- read.csv("1979-2019_monthly_Uganda.csv", header = TRUE)
# head(data)
# data format:
# lon | lat | year | month | pr | tasmin | tasmax

Uganda<-readOGR('./shp/UGA_adm1.shp', stringsAsFactors = FALSE) # preferred as it is being processed better by ggplot
```

# Prepare data

Get mean t and rainfall across all years. 

```{r}
# Precipitation
annual_pr<-aggregate(pr ~ lat+lon+year, data=data, sum, na.rm=TRUE) # precip mean over all years per lat & lon
annual_pr<-aggregate(pr ~ lat+lon, data=annual_pr, mean, na.rm=TRUE) # precip mean over all years per lat & lon

# Temperature
annual_tas<-aggregate(cbind(tasmax,tasmin) ~ lat+lon, data=data, mean, na.rm=TRUE)
annual_tas$tas<-rowMeans(annual_tas[,c('tasmin','tasmax')], na.rm=TRUE)

# Combine
annual_hist_means<-annual_pr
annual_hist_means$tas<-annual_tas$tas
```

# Map data
## Facet temp and precipitation

```{r}
ggplot() +
  geom_tile(data = annual_hist_means, aes(x = lon, y = lat, fill = pr)) +
  scale_fill_gradientn("mm/year", values = c(0, 0.3,0.6, 1),  # values can twist the legend
                       colours=c(brewer.pal(9,'BrBG')),
                       na.value = 'grey')+
  geom_polygon(data=Uganda, aes(x = long, y=lat, group=group), fill = NA, col="black", size = 0.9) + # for the country map
  geom_hline(yintercept=seq(-2,5,by=2), linetype="dashed", color = "black") + # for y-axis
  geom_vline(xintercept=seq(28,35,by=2), linetype="dashed", color = "black") + # for x-axis
  theme(axis.text=element_text(family="DejaVu Sans", size = rel(1.2)),
        axis.title.x=element_text(margin=margin(t=0.4, unit="cm"), size=13,family="DejaVu Sans"),
        axis.title.y=element_text(margin=margin(r=0.4, unit="cm"), size=13, family="DejaVu Sans"),
        axis.ticks.length = unit(0.2, "cm"),
        legend.title =element_text(size = 13, face = 'bold', family="DejaVu Sans", margin=margin(b=0.4, unit="cm")),
        legend.key.width = unit(0.35, "cm"), 
        legend.key.height = unit(0.8, "cm"),
        legend.text = element_text(family="DejaVu Sans", size = rel(1.2)),
        legend.position = "right")  +
  scale_x_continuous(breaks= seq(28,35,by=2), name= "Longitude (E)") +
  scale_y_continuous(breaks= seq(-2,5,by=2), name="Latitude (N)") +
  coord_map(xlim = c(29.5,35), ylim = c(-1.5,4.5)) 
```




```{r}
ggplot() +
  geom_tile(data = annual_hist_means, aes(x = lon, y = lat, fill = tas)) +
  scale_fill_gradientn("°C",limits=c(15,30), values = c(0, 0.4,0.6, 0.8, 1),  # values can twist the legend
                       colours=c(brewer.pal(9,'YlOrRd')),
                       na.value = 'grey')+
  geom_polygon(data=Uganda, aes(x = long, y=lat, group=group), fill = NA, col="black", size = 0.9) + # for the country map
  geom_hline(yintercept=seq(-2,5,by=2), linetype="dashed", color = "black") + # for y-axis
  geom_vline(xintercept=seq(28,35,by=2), linetype="dashed", color = "black") + # for x-axis
  theme(axis.text=element_text(family="DejaVu Sans", size = rel(1.2)),
        axis.title.x=element_text(margin=margin(t=0.4, unit="cm"), size=13,family="DejaVu Sans"),
        axis.title.y=element_text(margin=margin(r=0.4, unit="cm"), size=13, family="DejaVu Sans"),
        axis.ticks.length = unit(0.2, "cm"),
        legend.title =element_text(size = 13, face = 'bold', family="DejaVu Sans", margin=margin(b=0.4, unit="cm")),
        legend.key.width = unit(0.35, "cm"), 
        legend.key.height = unit(0.8, "cm"),
        legend.text = element_text(family="DejaVu Sans", size = rel(1.2)),
        legend.position = "right")  +
  scale_x_continuous(breaks= seq(28,35,by=2), name= "Longitude (E)") +
  scale_y_continuous(breaks= seq(-2,5,by=2), name="Latitude (N)") +
  coord_map(xlim = c(29.5,35), ylim = c(-1.5,4.5)) 
```
