---
title: "Uganda droughts (proj)"
author: "Albina Muzafarova"
output: html_notebook
---



```{r}
library(SPEI)
library(ggplot2) #for mapping with ggplot
library(scales)  #for colour scales
library(RColorBrewer) #for colour scales
library(zoo)
library(tidyverse)
library(tidyr)
library(dplyr)
```



```{r}
#load daily data
daily_all370<-read.csv("alls_ssp370_2014-2100_daily.csv", header =TRUE)
head(daily_all370)

#degress the models
monthly370<-simplify(daily_all370)

# calc speimemoe
petBal370<- petBalance(monthly370)
spei12_370<-droughts(petBal370)
df_spei12_370<-as.data.frame(spei12_370$fitted)
df_spei12_370<- rename(df_spei12_370, fitted=`Series 1`)
df_370<-graphPrep(df_spei12_370)

#write.csv(DF, "proj_370_spei_plotted_droughts.csv")


#### for 126
#load daily data
daily_all_126<-read.csv("alls_ssp126_2014-2100_daily.csv", header =TRUE)
head(daily_all_126)

monthly126<-simplify(daily_all_126)
petBal126<-petBalance(monthly126)
spei12_126<-droughts(petBal126)
df_spei12_126<-as.data.frame(spei12_126$fitted)
df_spei12_126<- rename(df_spei12_126, fitted=`Series 1`)

#write.csv(df_spei12_126, "proj_126_spei_droughts.csv")
df_126<-graphPrep(monthly, df_spei12_126)
#write.csv(df, "proj_126_spei_plotted_droughts.csv")
```

Helpers
```{r}
petBalance<-function(source) {
  combined<-data.frame(matrix(ncol = 10, nrow = 0))
  lats<-unique(source$lat)
  for(i in lats) {
    filtered<-filter(source, lat==i)
    filtered$PET<-thornthwaite(filtered$tasmean, i) #calculate potential evapotranspiration
    filtered$BAL <- filtered$pr-filtered$PET        #calculate balance
    combined<-rbind(combined, filtered)
  }
  write.csv(combined, "proj_126_pet_Uganda.csv", col.names = TRUE) #adapt title
  return(combined)
}

droughts<-function(source) {
  ts <- ts(source[,-c(1,2,3,4)], start=c(1981,1), frequency=12) #make time series for SPEI
  spei12 <- spei(ts[,'BAL'], 12) #calculate SPEI for one year
  return(spei12)
}

simplify<-function(source) {
  #degress the models
  pr_daily<-aggregate(pr ~ lon+lat+year+month+Date, source, mean, na.rm=TRUE)
  #monthly mean
  pr_month<-aggregate(pr ~ month+year, pr_daily, sum, na.rm=TRUE)
  write.csv(pr_month, "proj_126_pr_monthly_droughts.csv") #adapt title
  rm(pr_daily, pr_month) # to release memory
  gc()
  
  
  tas_daily<-aggregate(cbind(tasmax,tasmin) ~ lon+lat+year+month+Date, source, mean, na.rm=TRUE)
  tas_month<-aggregate(cbind(tasmax,tasmin) ~ month+year+lon+lat, tas_daily, mean, na.rm=TRUE)
  write.csv(tas_month, "proj_126_tas_monthly_droughts.csv") #adapt title
  rm(tas_daily)
  gc()
  
  pr_month<- read_csv("proj_126_pr_droughts.csv",  col_types = cols(...1 = col_skip()))
  
  data<-cbind(tas_month,pr_month$pr) 
  colnames(data)<-c("month","year","lon","lat","tasmin","tasmax","pr")
  data$tasmean <- (data$tasmax+data$tasmin)/2 
  
  return(data)
}

graphPrep<-function(source, spei) {
  df <- zoo::fortify.zoo(spei)
  df <- df %>% 
  dplyr::select(-Index) %>% 
  dplyr::mutate(Period = zoo::as.yearmon(paste(source$year, source$month), "%Y %m")) %>% 
  na.omit() %>% 
  dplyr::mutate(sign = ifelse(fitted >= 0, "pos", "neg"))
  return(df)
}
```

To map

```{r}
ggplot2::ggplot(df_370) +
  geom_bar(aes(x = Period, y = fitted, col = sign, fill = sign),
            show.legend = F, stat = "identity") +
  scale_color_manual(values = c("pos" = "darkblue", "neg" = "red")) +
  scale_fill_manual(values = c("pos"  = "darkblue", "neg" = "red")) +
  ylab("SPEI") + ggtitle("12-Month SPEI with ssp370") +
  theme_bw() + theme(plot.title = element_text(hjust = 0.5))
```
```{r}
ggplot2::ggplot(df_126) +
  geom_bar(aes(x = Period, y = fitted, col = sign, fill = sign),
            show.legend = F, stat = "identity") +
  scale_color_manual(values = c("pos" = "darkblue", "neg" = "red")) +
  scale_fill_manual(values = c("pos"  = "darkblue", "neg" = "red")) +
  ylab("SPEI") + ggtitle("12-Month SPEI with ssp126") +
  theme_bw() + theme(plot.title = element_text(hjust = 0.5))
```
